### ISSUE TITLE
tray.cs not found

### ISSUE THREAD

**Issue by Doncode** [jden/tray-windows#1]
I have  error.
Please help me for resolve this problem

d:\work\my\desktop\node_modules\tray-windows\node_modules\edge\lib\edge.js:154
    return edge.initializeClrFunc(options);
                ^
Error: Не удалось найти часть пути "d:\work\my\desktop\lib\tray.cs".
    at Error (native)
    at Object.exports.func (d:\work\my\desktop\node_modules\tray-windows\node_modules\edge\lib\edge.js:154:17)
    at Object.<anonymous> (d:\work\my\desktop\node_modules\tray-windows\index.js:7:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (d:\work\my\desktop\t.js:8:12)

**Comment by junosuarez** [comment]
My mistake! I've updated the path resolution - please update to `tray-windows@1.0.1` and try again.
